export enum AuditAction {
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  SCHEDULE_CREATED = 'SCHEDULE_CREATED',
  SCHEDULE_CONFIRMED = 'SCHEDULE_CONFIRMED',
  SCHEDULE_RESCHEDULED = 'SCHEDULE_RESCHEDULED',
  ORDER_TRANSPORT_CHANGED = 'ORDER_TRANSPORT_CHANGED',
}
